Repository mariogarridopt/mariobot, pull requests merged in 2023-04, with the labels that each got.

#2 feat: add build to the league role
  bot.py
  roll.py
Labels: enhancement, good first issue

#10 fix: add ChatGPT integration
  .env-example
  requirements.txt
  src/bot.py
  src/modules/ai_assitant.py
Labels: enhancement

#8 fix: timer cog not running
  src/bot.py
Labels: bug

#18 fix: Timer using lisbon Timezone
  Makefile
  src/modules/timer_cog.py
Labels: bug

#19 fix: update docs
  README.md
Labels: documentation

#17 feat: add minecraft server command
  .env-example
  .github/workflows/deploy.yml
  requirements.txt
  src/bot.py
  src/modules/ai_assitant.py
  src/modules/minecraft_server.py
  src/modules/react.py
  src/modules/timer_cog.py
Labels: feature
